baseURL = "https://seedfreelance.com/"
defaultContentLanguage = "en"
disableKinds = ["taxonomy", "term", "rss"]
enableGitInfo = false
timeout = "60s"

[build]
  [build.buildStats]
    enable = false

[imaging]
  quality = 80
  resampleFilter = "Lanczos"

[minify]
  [minify.tdewolff.html]
    keepQuotes = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5

[params]
  # Site-wide, language-independent parameters live in params.toml
